# this is config server application.yml file
# FILE: application.yml (In GitHub)
eureka:
  instance:
    prefer-ip-address: true
    # ADD THESE TWO LINES
    non-secure-port-enabled: false
    secure-port-enabled: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # CHANGE http TO https
      defaultZone: https://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: env, health, info, gateway
